version: '3'

services:
  database:
    image: postgres:16
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokebase
    volumes:
      - database-data:/var/lib/postgresql/data:rw

  api:
    build:
      context: .
      dockerfile: .docker/api/Dockerfile
    container_name: api
    links:
      - database
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html
      - ./.docker/api/apache/app.conf:/etc/apache2/conf-enabled/app.conf
      - ./.docker/api/php/20-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_NAME: pokebase

  front:
    build:
      context: .
      dockerfile: .docker/front/Dockerfile
    container_name: front
    links:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    stdin_open: true
    tty: true

volumes:
  database-data:
